SET (CPACK_PACKAGE_VENDOR "Eyenix")

set(CPACK_PACKAGE_VERSION_MAJOR ${VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${VERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${VERSION_PATCH})

SET ( CPACK_SOURCE_GENERATOR "ZIP" )

string(TIMESTAMP MAKE_CPACK_TIME "%y%m%d%H%M%S")
SET ( CPACK_SOURCE_PACKAGE_FILE_NAME "en675_fpga_rc${VERSION_MAJOR}${VERSION_MINOR}${VERSION_PATCH}_${MAKE_CPACK_TIME}" )

set (CPACK_SOURCE_IGNORE_FILES "_CPack_Packages;.bak;/CVS/;/\\\\.svn/;/\\\\.bzr/;/\\\\.hg/;/\\\\.git/;\\\\.swp\$;\\\\.#;/#" )

INCLUDE ( CPack )
